spring:
  data:
    mongodb:
      uri: mongodb://team_document_db:27017/team_document_db

teamdocument:
  userName: ${USER_NAME}
  userPassword: ${USER_PASSWORD}
  allowedOrigins: https://test-pebs.ch/, https://test-pebs.ch
  server:
    commands:
      serve-sender-id: fcd6e222-074b-4d04-9af6-062bfcd8402e
