spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/team_document_db

teamdocument:
  userName: User
  userPassword: 1234
  allowedOrigins: 'http://localhost:3000/*'

logging:
  level:
    org:
      springframework:
        security: DEBUG